version: '2'
services:
 web:
   build:
    context: .
    dockerfile: ./Dockerfile
   depends_on:
    - mysql
   ports:
    - "8080:80"
 mysql:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=magento
