version: '2'
services:
  couchdb:
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
    environment:
      COUCHDB_USER: vulhub
      COUCHDB_PASSWORD: vulhub
