version: '2'
services:
 web:
   build:
      context: .
      dockerfile: ./Dockerfile 
   depends_on:
    - mysql
   environment: 
    - WORDPRESS_DB_HOST=mysql:3306
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=root
    - WORDPRESS_DB_NAME=wordpress
   ports:
    - "8081:80"
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
