version: '2'
services:
 web:
   build:
    context: .
    dockerfile: ./Dockerfile
   ports:
    - "8080:80"
   volumes:
    - ./safe.cgi:/var/www/html/safe.cgi
    - ./victim.cgi:/var/www/html/victim.cgi